77 validacao administrador exclusao equipamento
fga-eps-mds/2023-1-Alectrion-EquipamentApi pull request #10
Opened 2023-05-10 01:52 UTC by pedroyen21

## Modificações
Adicionada a restrição de acesso à exclusão de equipamentos
## Descrição
Apenas administradores podem excluir equipamentos
## _Issue_ relacionado
77

## Como foi testado?
Testes automatizados  com requisições e postman
## Imagens:
## Tipo de modificações
- [] Nova _feature_

## Lista de controle:
- [] Meu _commits_ segue a política de commits do repo.
- [] Adicionei testes para cobrir minhas modificações.
- [] Todos os testes foram aprovados.

2023-05-15 02:27 UTC, JoaoVitorFarias reviewed
As demais mudanças já foram comentadas na [PR 45](https://github.com/fga-eps-mds/2023-1-Alectrion-EquipamentApi/pull/9). Depois da correção precisa fazer o merge nessa branch

2023-05-15 02:27 UTC, JoaoVitorFarias commented on tests/deleteEquipmentController.spec.ts
> +/* describe('admin request tests', () => {
Remover código comentado

2023-05-16 12:46 UTC, JoaoVitorFarias approved these changes

2023-05-20 00:17 UTC, AlineLermen approved these changes

2023-05-20 00:21 UTC, AlineLermen requested changes
Os testes estão falhando e há conflito no arquivo de rotas

2023-05-20 01:07 UTC, pedroyen21 commented
Depois que eu fiz o merge os testes começaram a dar erro, tentei solucionar, mas não consegui. Como foi dito que escrevê-los não era mais nossa incumbência, resolvi entregar o mais rápido possível.

Sobre o conflito no arquivo de rotas, eu não tenho na minha branch a funcionalidade de edição de equipamento. Se eu aceitar essa rota vai dar erro. É só tirar?

2023-05-20 15:09 UTC, AlineLermen commented
> Depois que eu fiz o merge os testes começaram a dar erro, tentei solucionar, mas não consegui. Como foi dito que escrevê-los não era mais nossa incumbência, resolvi entregar o mais rápido possível.
> 
> Sobre o conflito no arquivo de rotas, eu não tenho na minha branch a funcionalidade de edição de equipamento. Se eu aceitar essa rota vai dar erro. É só tirar?

Ok. Sobre o conflito, ele é relacionado a quando for feito o merge na develop. A funcionalidade de edição existe na develop, e a rota da edição está na mesma linha que a rota de exclusão. As duas rotas são necessárias, ou seja, devem ser mantidas no arquivo

2023-05-25 12:52 UTC, JPedroCh approved these changes
LGTM

2023-05-25 12:57 UTC, merged