103 filtros de ordem de servico
fga-eps-mds/2023-1-Alectrion-EquipamentApi pull request #30
Opened 2023-06-04 18:51 UTC by Izarias

## Modificações
Altera a função para encontrar ordens de serviço por data de update, tipo de equipamento, unidade do equipamento, marca do equipamento, status da ordem de serviço e etc.
Corrige um erro de ortografia no nome da rota.
## _Issue_ relacionado
103
## Motivação e Contexto
Adaptar a função para filtrar ordens de serviço no front
## Como foi testado?
Teste unitário já existente
## Tipo de modificações
-  _ ​​correção de bug_
- [ ] Nova _feature_

## Lista de controle:
-  Meu código segue a folha de estilos implementada
- [ ] Meu _commits_ segue a política de commits do repo.
- [ ] Minhas modificações requerem modificações na documentação atual.
-  Atualizei a Documentação
-  Adicionei testes para cobrir minhas modificações.
- [ ] Todos os testes foram aprovados.

2023-06-04 19:59 UTC, JPedroCh requested changes
Tem um caso de teste que não está mais passando, o qual deve ser ajustado.

2023-06-06 14:02 UTC, JPedroCh requested changes
Ao passar o "search" na url da request estou recebendo o seguinte erro, o qual acredito que esteja incorreto:
	"error": "invalid input syntax for type date: \"Invalid date\""

2023-06-06 16:40 UTC, AlineLermen approved these changes

2023-06-06 22:35 UTC, JPedroCh approved these changes
LGTM!

2023-06-06 22:36 UTC, merged